tencent:
  cloud:
    appId: ************
    secretId: ************
    secretKey: ************
    region: ************
    bucket: ************
  trtc:
    appId: ************
    secretKey: ************
    expire: ************
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: cdu.gu.trtc.dao
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true